### ISSUE TITLE
kin-openapi@v0.115.0/openapi2/doc.go:1:1: expected 'package', found 'EOF'

### ISSUE THREAD

**Issue by r00tk1ll** [BishopFox/sj#40] opened 2024-11-20 12:38 UTC
On the latest VHD of Kali Linux I get the following error when trying to run the command from the sj/ directory:

`go build .`

```
/root/go/pkg/mod/github.com/getkin/kin-openapi@v0.115.0/openapi2/doc.go:1:1: expected 'package', found 'EOF'
/root/go/pkg/mod/github.com/getkin/kin-openapi@v0.115.0/openapi2conv/doc.go:1:1: expected 'package', found 'EOF'
/root/go/pkg/mod/github.com/getkin/kin-openapi@v0.115.0/openapi3/callback.go:1:1: expected 'package', found 'EOF'
```

This probably is related to go somehow, I'm just unfamiliar with the language. Could you help me out here?

Thanks

**Comment by twest-bf** [comment] 2024-11-22 15:31
Can you run the following commands from the sj directory and share the output here?

```bash
$ go version
$ cat go.mod
```

Alternatively, you can install using `$ go install github.com/BishopFox/sj@latest`

**Comment by r00tk1ll** [comment] 2024-11-25 00:25
Here you go:

`go version go1.23.3 linux/amd64

module github.com/BishopFox/sj

go 1.20

require (
        github.com/getkin/kin-openapi v0.115.0
        github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de
        github.com/sirupsen/logrus v1.9.0
        github.com/spf13/cobra v1.6.1
        golang.org/x/time v0.8.0
        gopkg.in/yaml.v3 v3.0.1
)

require (
        github.com/go-openapi/jsonpointer v0.19.5 // indirect
        github.com/go-openapi/swag v0.19.5 // indirect
        github.com/inconshreveable/mousetrap v1.0.1 // indirect
        github.com/invopop/yaml v0.1.0 // indirect
        github.com/josharian/intern v1.0.0 // indirect
        github.com/mailru/easyjson v0.7.7 // indirect
        github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826 // indirect
        github.com/perimeterx/marshmallow v1.1.4 // indirect
        github.com/spf13/pflag v1.0.5 // indirect
        golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8 // indirect
        gopkg.in/yaml.v2 v2.4.0 // indirect
)

└─# go install github.com/BishopFox/sj@latest
/root/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20241115213015-585100037a3a/main.go:1:1: expected 'package', found 'EOF'
`

Any idea whats going on?

**Comment by twest-bf** [comment] 2024-11-25 16:24
Weird, I'm not sure.. using `go 1.23.3 linux/amd64` I'm unable to reproduce on my end. Are you able to reach the repository with curl?

**Comment by r00tk1ll** [comment] 2024-11-25 19:33
I can reach it with curl. Is there a way to just remove everything including go and start over from scratch?

**Comment by twest-bf** [comment] 2024-11-25 20:56
Yeah you can just remove your go installation directory and the repository and then reinstall both:

```bash
$ rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.3.linux-amd64.tar.gz
$ go install github.com/BishopFox/sj@latest
```

**Comment by r00tk1ll** [comment] 2024-11-26 00:18
The install command gives this (so weird):

`# go install github.com/BishopFox/sj@latest
/root/go/pkg/mod/github.com/!bishop!fox/sj@v0.0.0-20241115213015-585100037a3a/main.go:1:1: expected 'package', found 'EOF'`

**Comment by twest-bf** [comment] 2024-11-27 19:32
You could try again after running `$ go clean -cache` possibly, but I'm not sure if that will help.

**Comment by twest-bf** [comment] 2024-12-17 22:53
Closing issue for now, will reopen if necessary

**Closed by twest-bf** 2024-12-17 22:53 UTC
Labels: question
